language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
- name: FallbackPolicy
  nlu_threshold: 0.1
  core_threshold: 0.1
  fallback_action_name: action_default_fallback
- name: DucklingHTTPExractor
  url: http://localhost:8000
  dimensions:
  - time
  locale: en_UK
  timezone: Europe/Berlin
